title: "levolution.info"
description: "@skyriser personal portal / 'Levo Lution' official web"
domain: levolution.info
url: https://levolution.info
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
